title: Rust Penguin
email: korean.ruster@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  러스트와 관련하여 다루는 페이지입니다.
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed